# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

larscpp <- function(x, beta, y, maxk) {
    .Call('ccs_larscpp', PACKAGE = 'ccs', x, beta, y, maxk)
}

lassocpp <- function(x, beta, y, maxk) {
    .Call('ccs_lassocpp', PACKAGE = 'ccs', x, beta, y, maxk)
}

